{
    "bayelsa": {
        "brass": {
            "local_point": [4.3078, 6.2456]
            "twon-brass": []
            "okpoama": []
            "ewoama": []
            "sangana": []
            "odioma": []
            "ibidi": []
            "konsho": []
            "cape farmosa": []
            "kaiko/ibewo": []
            "akassa": []
        }
        "ekeremor": {
            "local_point": [5.0563, 5.7813]
            "agge": []
        }
        "kolokuma/opokuma": {
            "local_point": [5.092, 6.2588]
            "kaiama": []
            "odi": []
        }
        "nembe": {
            "local_point": [4.4942, 6.2801]
            "oluasiri": []
            "okoroma": []
            "ogbolomabiri": []
            "bassambiri": []
            "igbeta-ewoama": []
            "ikensi": []
            "mini": []
            "egebekiri": []
        }
        "ogbia": {
            "local_point": [4.7399, 6.3652]
            "otuoke": []
            "kolo": []
            "oloibiri": []
            "otuokpoti": []
            "anyama": []
            "imiringi": []
            "opume": []
            "otuogori": []
            "iduma": []
            "obeduma": []
            "ologi": []
            "okodi": []
            "otuasega": []
            "emeyal": []
            "otakeme": []
            "otuabula": []
        }
        "sagbama": {
            "local_point": [5.1593, 6.1971]
            "egbemo-angalabiri": []
            "otoni": []
            "ossiama": []
            "adagbabiri": []
            "adoni": []
            "agbere": []": []
            "asamabiri": []
            "ebedebiri": []
            "osekwenike": []
            "agoro": []
            "toru ebeni": []
            "trotani": []
            "foropa": []
            "orua": []
            "ofoni": []
            "odoni": []
            "trofani": []
        }
        "southern ijaw": {
            "local_point": [4.6198, 5.9833]
            "ogboinbiri": []
            "oporoma": []
            "koluama": []
            "olodiama": []
            "otuan": []": []
            "ukubie": []
            "west boma": []
            "amassoma": []
            "apoi central": []
            "ogboinbiri": []
            "boma Central": []
            "east Boma": []
            "foropa": []
            "keme-ebiama": []
            "ikebiri": []
        }
        "yenagoa": {
            "local_point": [4.9514, 6.3492]
            "famgbe": []
            "tombia": []
            "etegwe": []
            "zarama": []
            "okordia": []
            "biseni": []
            "epie-attissa": []
            "gbarain": []
            "ekpetiama": []
            "biseni": []
            "amarata": [6.28818, 4.92812]
            "onopa": []
            "yenezuegene": []
            "biogbolo": []
            "igbogene": []
            "opolo": []
        }
    }
    "benue": {
        "ado": {
            "local_point": [7.7962, 7.7641]
            "agila": []
            "igumale": []
            "ulayi": []
            "ochekwu": []
            "atonkon": []
            "utonkon": []
        }
        "agatu": {
            "local_point": [7.8412, 7.9157]
            "obagaji": []
            "ocholonya": []
            "aila": []
            "okokolo": []
            "adagbo": []
            "akwu": []
            "omikuidi": []
            "odugbeho": []
            "akpeko": []
            "oweto": []
        }
        "apa": {
            "local_point": [7.8711, 7.6296]
            "ochekwu": []
            "oiji": []
            "odugbo": []
            "ikobi": []
            "iga-okpaya": []
            "idada": []
        }
        "buruku": {
            "local_point": [7.4178, 9.2231]
            "shorov": []
            "utur": []
            "etilo": []
            "mbaakura": []
            "binev": []
            "mbaade": []
            "mbaatirkya": []
            "mbaazager": []
            "mbarkyongo": []
            "mbatyough": []
            "mbaya": []
            "mbayaka": []
        }
        "gboko": {
            "local_point": [7.3368, 9.0018]
            "gboko east": []
            "gboko north west": []
            "gboko south": []
            "igyorov": []
            "mbaa varakaa": []
            "mbaanku": []
            "mbadam": []
            "mbakper": []
        }
        "guma": {
            "local_point": [7.9541, 8.7481]
            "gbajimba": []
            "mbaawa": []
            "mbabai": []
            "mbasaan ": []
            "mbagwen": []
            "uyiev": []
            "abinsi": []
            "kase-yough": []
            "torkula": []
            "daudu": []
        }
        "gwer east": {
            "local_point": [7.445, 8.3965]
            "ingohov": []
            "njiriv": []
            "raav": []
            "yonov": []
            "mbakpa": []
        }
        "gwer west": {
            "local_point": [7.6639, 8.1776]
            "sengev": []
            "tsambe/mbesev": []
            "merkyen": []
            "nyamshi": []
            "gaambe-ushin": []
            "mbachohon": []
            "mbakpa": []
            "tijime": []
            "avihijime.": []
            "gbange/tongov": []
            "toughatee/injaha": []
            "yengev": []
            "ukusu": []
            "ikyagev": []
            "mbabuande": []
        }
        "katsina-ala": {
            "local_point": [7.1658, 9.2841]
            "ikyurav-tiev i": []
            "ikyurav-tiev ii": []
            "yooyo": []
            "utange": []
            "tiir": []
            "iwar": []
            "michihe": []
            "mbakyongo": []
            "mbajir": []
            "mbatyura/mberev": []
            "mbacher": []
        }
        "konshisha": {
            "local_point": [7.0997, 8.5721]
            "mbaiwarnyam": []
            "mbatsen": []
            "ikyurav/mbatwer": []
            "mbayegh/mbaikyer": []
            "tse-agberagba": []
            "mbavaa": []
            "mbanor": []
            "mbatser/mbagusa": []
            "mbake": []
            "mbawar": []
            "mbaikyase": []
        }
        "kwande": {
            "local_point": [6.9126, 9.4562]
            "adikpo-nanev": []
            "liev i": []
            "liev ii": []
            "mbadura": []
            "mbagba/mbakyan": []
            "mbaikyor_turan": []
            "mbaketsa": []
            "menev-ikyura-ya": []
            "tondov i": []
            "tondov ii": []
            "usar": []
            "mbayoo": []
            "yaav": []
            "moon-turan": []
            "kumakwagh": []
        }
        "logo": {
            "local_point": [7.5987, 9.2786]
            "mbadyul": []
            "mbagber": []
            "mbater": []
            "mbavuur": []
            "mbayam": []
            "nenzev": []
            "tombo": []
            "turan": []
            "ukembergya/iswarev": []
            "yonov": []
        }
        "makurdi": {
            "local_point": [7.7322, 8.5391]
            "agan": []
            "bar": []
            "central-south mission": []
            "clerk or market": []
            "fiidi": []
            "mbalagh": []
            "modern market": []
            "north bank i": []
            "north bank ii": []
            "wailomayo": []
        }
        "obi": {
            "local_point": [8.3688, 8.7715]
            "obarike-ito": []
            "orihi": []
            "okwutungbe": []
            "ogore": []
            "okpokwu": []
            "odiapa": []
            "obeko": []
            "itogo": []
            "irabi": []
            "ikwokwu": []
            "akum west": []
            "adiko": []
        }
        "ogbadibo": {
            "local_point": [6.9876, 7.6548]
            "otukpa": []
            "orokam": []
            "owukpa": []
        }
        "ohimini": {
            "local_point": [7.2396, 7.9157]
            "ochobo": []
            "onyangede": []
            "agadagba": []
            "atilo": []
            "awulema": []
            "awule": []
            "ugene": []
            "ehatokpe": []
            "ojali": []
            "ojano": []
            "okete": []
            "ankpechi": []
        }
        "oju": {
            "local_point": [6.8398, 8.415]
            "adokpa": []
            "ibilla": []
            "idelle": []
            "iyeche": []
            "oboru oye": []
            "okpokpo ": []
            "okudu": []
            "owo": []
            "ukpa": []
            "ainu": []
        }
        "okpokwu": {
            "local_point": [7.0701, 7.8286]
            "ameju": []
            "eke": []
            "ichama i": []
            "ichama ii": []
            "ingle-okpale": []
            "ojigo": []
            "okonobo": []
            "okpoga central": []
            "okpoga north": []
            "okpoga south": []
            "okpoga west": []
            "ugbokolo": []
        }
        "oturkpo": {
            "local_point": [7.1982, 8.1393]
            "umogidi": []
            "icho": []
            "haje": []
            "allan": []
            "entekpa": []
            "ewulo": []
            "okete": []
            "otobi": []
            "otahe": []
            "ehaje": []
            "oturkpo central": []
            "oturkpo east": []
            "oturkpo west": []
        }
        "tarka": {
            "local_point": [7.6299, 8.8142]
            "shitile": []
            "tongov": []
            "mbakwakem": []
            "mbaajir": []
            "mbaigba": []
            "mbachaverikyondo": []
            "mbaikyo-mbayia": []
            "mbaayo": []
            "mbanyagber": []
            "mbaikyaa": []
        }
        "ukum": {
            "local_point": [7.5909, 9.6341]
            "aterayange": []
            "mbatian": []
            "boikyo": []
            "uyan": []
            "ugbam": []
            "ituluv": []
            "lumbuv": []
            "mbazun": []
            "tsaav": []
            "mbayenge": []
            "azendeshi": []
            "kendav": []
            "kundav": []
        }
        "ushongo": {
            "local_point": [6.947, 9.255]
            "atirkyese": []
            "ikov": []
            "lessel": []
            "mbaaka": []
            "mbaanyam": []
            "mbaawe": []
            "mbagba": []
            "mbagwaza": []
            "mbakuha": []
            "mbayegh": []
            "utange": []
        }
        "vandeikya": {
            "local_point": [6.7835, 9.0695]
            "mbagbam": []
            "mbadede": []
            "mbagbera": []
            "mbajor": []
            "mbayongo": []
            "mbakaange": []
            "nyimangbah": []
            "ningev": []
            "mbatyough": []
            "tsambe": []
            "mbakyaha": []
        }
    }
    "borno": {
        "abadam": {
            "local_point": [13.6182, 13.2649]
            "arege": []
            "banowa": []
            "fuguwa": []
            "jabullam": []
            "kudokurgu": []
            "mallam fatori kessa": []
            "malam kaunari": []
            "yau": []
            "yawa kura": []
            "yituwa": []
        }
        "askira/uba": {
            "local_point": [10.6563, 13.1279]
            "askira east": []
            "chul/romirgo": []
            "dille/huyum": []
            "husara/tampul": []
            "kopa/multhafu": []
            "lassa": []
            "mussa": []
            "ngohi": []
            "ngulde": []
            "uba": []
            "uda/uvu": []
            "wamdeo/giwi": []
            "zadawa/hausari": []
        }
        "bama": {
            "local_point": [11.5218, 13.6884]
            "andara": []
            "wulba": []
            "buduwa": []
            "bula chirabe": []
            "dipchari": []
            "dar-el-jamal": []
            "kotembe": []
            "gulumba": []
            "wuro bara": []
            "kumshe": []
            "nduguno": []
            "malam": []
            "mastari": []
            "abbaram": []
            "marka": []
            "malge": []
            "amchaka": []
            "mbuliya": []
            "goniri": []
            "siraja": []
            "soye": []
            "bulongu": []
            "shehuri": []
            "wulba": []
            "ndine soho": []
            "chachile": []
            "yabiri": []
            "kura": []
            "chongolo": []
            "zangeri"
            "kash kash bulali": []
        }
        "bayo": {
            "local_point": [10.2729, 11.6613]
            "balbaya": []
            "briyel": []
            "fikayel": []
            "gamadadi": []
            "jara dali": []
            "jara gol": []
            "limanti": []
            "teli": []
            "wuyo": []
            "zara": []
        }
        "biu": {
            "local_point": [10.6117, 12.1919]
            "Buratai": []
            "Dadin Kowa": []
            "Dugja": []
            "Garubula": []
            "Gur": []
            "Kenken": []
            "Mandara Girau": []
            "Miringa": []
            "Sulumthla": []
            "Yawi": []
            "Zarawuyaku": []
        }
        "chibok": {
            "local_point": [10.8692, 12.8476]
            "garu": []
            "likama": []
            "wuntaku": []
            "gatamarwa": []
            "kautikari": []
            "korongilim": []
            "kuburmbula": []
            "mbalala": []
            "mboa kura": []
            "pemi": []
            "shikarkir": []
        }
        "damboa": {
            "local_point": [11.1561, 12.7566]
            "ajign b": []
            "ajign ii": []
            "azir multe/forfor": []
            "yerwa": []
            "ngurna/bego": []
            "gumsuri/misakurbudu": []
            "kafa": []
            "Nguda": []
            "wuyaram": []
            "wawa/korede": []
        }
        "dikwa": {
            "local_point": [12.042, 13.9173]
            "boboshe": []
            "dikwa": []
            "gajibo": []
            "magarta/sheffri": []
            "mallam maja": []
            "mudu": []
            "Kaza": []
            "muliye: []
            "jemuri": []
            "ngudoram": []
            "sogoma": []
            "afuye": []
            "Ufaye/Gujile": []
        }
        "gubio": {
            "local_point": [12.4955, 12.7796]
            "ardimini": []
            "dabira": []
            "felo": []
            "gamowo": []
            "gazabure": []
            "gubio town i": []
            "gubio town ii": []
            "kingowa": []
            "ngetra": []
            "zowo": []
        }
        "guzamala": {
            "local_point": [12.8817, 13.2202]
            "aduwa": []
            "gudumbali east": []
            "gudumbali west": []
            "guworam": []
            "guzamala east": []
            "guzamala west": []
            "kingarwa": []
            "mairari": []
            "moduri": []
            "wamiri": []
        }
        "gwoza": {
            "local_point": [12.8817, 13.2202]
            "ashigashiya": []
            "bita/izge": []
            "dure": []
            "wala/warabe": []
            "gava/agapalwa": []
            "guduf": []
            "hausari": []
            "bulabulin": []
            "New Settlement": []
            "chikide": []
            "kughum": []
            "Kirawa": []
            "Kuranabassa": []
            "ngoshe": []
            "Pulka/bokko": []
        }
        "hawul": {
            "local_point": [10.4676, 12.3464]
            "bilingwi": []
            "dzar/ vinadum/ birni/ dlandi": []
            " gwanzang pusda": []
            "hizhi": []
            "kida": []
            " kwajaffa/hang": []
            " kwaya-bur/tanga rumta": []
            " marama/kidang": []
            " pama/whitambaya": []
            " puba/vidau/lokoja": []
            " sakwa/hema": []
            "shaffa": []
        }
        "jere": {
            "local_point": [11.8948, 13.2202]
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "kaga": {
            "local_point": [11.5246, 12.5298]
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "kala/balge": {
            "local_point": [12.0825, 14.4672]
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "konduga": {
            "local_point": [11.6549, 13.4197]
            "kasugula": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "kukawa": {
            "local_point": [12.9200, 13.5700]
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "kwaya kusar": {
            "local_point": [10.49577, 11.83711]
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "mafa": {
            "local_point": [11.924, 13.5987]
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "magumeri": {
            "local_point": [12.1151, 12.8256]
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "maiduguri": {
            "local_point": [11.8407, 13.1537]
            "mairi": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "marte": {
            "local_point": [12.3641, 13.8277]
            "lawanti": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "mobbar": {
            "local_point": [13.133, 12.7135]
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "monguno": {
            "local_point": [12.6729, 13.616]
            "bego": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "ngala": {
            "local_point": [12.3421, 14.1858]
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "nganzai": {
            "local_point": [12.5736, 13.0818]
            "sabsabwa": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "shani": {
            "local_point": [10.2227, 12.0518]
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
    }
    "cross river": {
          "lga": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
    }
    "delta": {
          "lga": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "lga": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "lga": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "lga": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "lga": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "lga": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "lga": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "lga": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "lga": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "lga": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "lga": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "lga": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "lga": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "lga": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
    }
}