{
    "bayelsa": {
        "brass": {
            "local_point": [4.3078, 6.2456]
            "twon-brass": []
            "okpoama": []
            "ewoama": []
            "sangana": []
            "odioma": []
            "ibidi": []
            "konsho": []
            "cape farmosa": []
            "kaiko/ibewo": []
            "akassa": []
        }
        "ekeremor": {
            "local_point": [5.0563, 5.7813]
            "agge": []
        }
        "kolokuma/opokuma": {
            "local_point": [5.092, 6.2588]
            "kaiama": []
            "odi": []
        }
        "nembe": {
            "local_point": [4.4942, 6.2801]
            "oluasiri": []
            "okoroma": []
            "ogbolomabiri": []
            "bassambiri": []
            "igbeta-ewoama": []
            "ikensi": []
            "mini": []
            "egebekiri": []
        }
        "ogbia": {
            "local_point": [4.7399, 6.3652]
            "otuoke": []
            "kolo": []
            "oloibiri": []
            "otuokpoti": []
            "anyama": []
            "imiringi": []
            "opume": []
            "otuogori": []
            "iduma": []
            "obeduma": []
            "ologi": []
            "okodi": []
            "otuasega": []
            "emeyal": []
            "otakeme": []
            "otuabula": []
        }
        "sagbama": {
            "local_point": [5.1593, 6.1971]
            "egbemo-angalabiri": []
            "otoni": []
            "ossiama": []
            "adagbabiri": []
            "adoni": []
            "agbere": []": []
            "asamabiri": []
            "ebedebiri": []
            "osekwenike": []
            "agoro": []
            "toru ebeni": []
            "trotani": []
            "foropa": []
            "orua": []
            "ofoni": []
            "odoni": []
            "trofani": []
        }
        "southern ijaw": {
            "local_point": [4.6198, 5.9833]
            "ogboinbiri": []
            "oporoma": []
            "koluama": []
            "olodiama": []
            "otuan": []": []
            "ukubie": []
            "west boma": []
            "amassoma": []
            "apoi central": []
            "ogboinbiri": []
            "boma Central": []
            "east Boma": []
            "foropa": []
            "keme-ebiama": []
            "ikebiri": []
        }
        "yenagoa": {
            "local_point": [4.9514, 6.3492]
            "famgbe": []
            "tombia": []
            "etegwe": []
            "zarama": []
            "okordia": []
            "biseni": []
            "epie-attissa": []
            "gbarain": []
            "ekpetiama": []
            "biseni": []
            "amarata": [6.28818, 4.92812]
            "onopa": []
            "yenezuegene": []
            "biogbolo": []
            "igbogene": []
            "opolo": []
        }
    }
    "benue": {
        "ado": {
            "local_point": [7.7962, 7.7641]
            "agila": []
            "igumale": []
            "ulayi": []
            "ochekwu": []
            "atonkon": []
            "utonkon": []
        }
        "agatu": {
            "local_point": [7.8412, 7.9157]
            "obagaji": []
            "ocholonya": []
            "aila": []
            "okokolo": []
            "adagbo": []
            "akwu": []
            "omikuidi": []
            "odugbeho": []
            "akpeko": []
            "oweto": []
        }
        "apa": {
            "local_point": [7.8711, 7.6296]
            "ochekwu": []
            "oiji": []
            "odugbo": []
            "ikobi": []
            "iga-okpaya": []
            "idada": []
        }
        "buruku": {
            "local_point": [7.4178, 9.2231]
            "shorov": []
            "utur": []
            "etilo": []
            "mbaakura": []
            "binev": []
            "mbaade": []
            "mbaatirkya": []
            "mbaazager": []
            "mbarkyongo": []
            "mbatyough": []
            "mbaya": []
            "mbayaka": []
        }
        "gboko": {
            "local_point": [7.3368, 9.0018]
            "gboko east": []
            "gboko north west": []
            "gboko south": []
            "igyorov": []
            "mbaa varakaa": []
            "mbaanku": []
            "mbadam": []
            "mbakper": []
        }
        "guma": {
            "local_point": [7.9541, 8.7481]
            "gbajimba": []
            "mbaawa": []
            "mbabai": []
            "mbasaan ": []
            "mbagwen": []
            "uyiev": []
            "abinsi": []
            "kase-yough": []
            "torkula": []
            "daudu": []
        }
        "gwer east": {
            "local_point": [7.445, 8.3965]
            "ingohov": []
            "njiriv": []
            "raav": []
            "yonov": []
            "mbakpa": []
        }
        "gwer west": {
            "local_point": [7.6639, 8.1776]
            "sengev": []
            "tsambe/mbesev": []
            "merkyen": []
            "nyamshi": []
            "gaambe-ushin": []
            "mbachohon": []
            "mbakpa": []
            "tijime": []
            "avihijime.": []
            "gbange/tongov": []
            "toughatee/injaha": []
            "yengev": []
            "ukusu": []
            "ikyagev": []
            "mbabuande": []
        }
        "katsina-ala": {
            "local_point": [7.1658, 9.2841]
            "ikyurav-tiev i": []
            "ikyurav-tiev ii": []
            "yooyo": []
            "utange": []
            "tiir": []
            "iwar": []
            "michihe": []
            "mbakyongo": []
            "mbajir": []
            "mbatyura/mberev": []
            "mbacher": []
        }
        "konshisha": {
            "local_point": [7.0997, 8.5721]
            "mbaiwarnyam": []
            "mbatsen": []
            "ikyurav/mbatwer": []
            "mbayegh/mbaikyer": []
            "tse-agberagba": []
            "mbavaa": []
            "mbanor": []
            "mbatser/mbagusa": []
            "mbake": []
            "mbawar": []
            "mbaikyase": []
        }
        "kwande": {
            "local_point": [6.9126, 9.4562]
            "adikpo-nanev": []
            "liev i": []
            "liev ii": []
            "mbadura": []
            "mbagba/mbakyan": []
            "mbaikyor_turan": []
            "mbaketsa": []
            "menev-ikyura-ya": []
            "tondov i": []
            "tondov ii": []
            "usar": []
            "mbayoo": []
            "yaav": []
            "moon-turan": []
            "kumakwagh": []
        }
        "logo": {
            "local_point": [7.5987, 9.2786]
            "mbadyul": []
            "mbagber": []
            "mbater": []
            "mbavuur": []
            "mbayam": []
            "nenzev": []
            "tombo": []
            "turan": []
            "ukembergya/iswarev": []
            "yonov": []
        }
        "makurdi": {
            "local_point": [7.7322, 8.5391]
            "agan": []
            "bar": []
            "central-south mission": []
            "clerk or market": []
            "fiidi": []
            "mbalagh": []
            "modern market": []
            "north bank i": []
            "north bank ii": []
            "wailomayo": []
        }
        "obi": {
            "local_point": [8.3688, 8.7715]
            "obarike-ito": []
            "orihi": []
            "okwutungbe": []
            "ogore": []
            "okpokwu": []
            "odiapa": []
            "obeko": []
            "itogo": []
            "irabi": []
            "ikwokwu": []
            "akum west": []
            "adiko": []
        }
        "ogbadibo": {
            "local_point": [6.9876, 7.6548]
            "otukpa": []
            "orokam": []
            "owukpa": []
        }
        "ohimini": {
            "local_point": [7.2396, 7.9157]
            "ochobo": []
            "onyangede": []
            "agadagba": []
            "atilo": []
            "awulema": []
            "awule": []
            "ugene": []
            "ehatokpe": []
            "ojali": []
            "ojano": []
            "okete": []
            "ankpechi": []
        }
        "oju": {
            "local_point": [6.8398, 8.415]
            "adokpa": []
            "ibilla": []
            "idelle": []
            "iyeche": []
            "oboru oye": []
            "okpokpo ": []
            "okudu": []
            "owo": []
            "ukpa": []
            "ainu": []
        }
        "okpokwu": {
            "local_point": [7.0701, 7.8286]
            "ameju": []
            "eke": []
            "ichama i": []
            "ichama ii": []
            "ingle-okpale": []
            "ojigo": []
            "okonobo": []
            "okpoga central": []
            "okpoga north": []
            "okpoga south": []
            "okpoga west": []
            "ugbokolo": []
        }
        "oturkpo": {
            "local_point": [7.1982, 8.1393]
            "umogidi": []
            "icho": []
            "haje": []
            "allan": []
            "entekpa": []
            "ewulo": []
            "okete": []
            "otobi": []
            "otahe": []
            "ehaje": []
            "oturkpo central": []
            "oturkpo east": []
            "oturkpo west": []
        }
        "tarka": {
            "local_point": [7.6299, 8.8142]
            "shitile": []
            "tongov": []
            "mbakwakem": []
            "mbaajir": []
            "mbaigba": []
            "mbachaverikyondo": []
            "mbaikyo-mbayia": []
            "mbaayo": []
            "mbanyagber": []
            "mbaikyaa": []
        }
        "ukum": {
            "local_point": [7.5909, 9.6341]
            "aterayange": []
            "mbatian": []
            "boikyo": []
            "uyan": []
            "ugbam": []
            "ituluv": []
            "lumbuv": []
            "mbazun": []
            "tsaav": []
            "mbayenge": []
            "azendeshi": []
            "kendav": []
            "kundav": []
        }
        "ushongo": {
            "local_point": [6.947, 9.255]
            "atirkyese": []
            "ikov": []
            "lessel": []
            "mbaaka": []
            "mbaanyam": []
            "mbaawe": []
            "mbagba": []
            "mbagwaza": []
            "mbakuha": []
            "mbayegh": []
            "utange": []
        }
        "vandeikya": {
            "local_point": [6.7835, 9.0695]
            "mbagbam": []
            "mbadede": []
            "mbagbera": []
            "mbajor": []
            "mbayongo": []
            "mbakaange": []
            "nyimangbah": []
            "ningev": []
            "mbatyough": []
            "tsambe": []
            "mbakyaha": []
        }
    }
    "borno": {
        "abadam": {
            "local_point": [13.6182, 13.2649]
            "arege": []
            "banowa": []
            "fuguwa": []
            "jabullam": []
            "kudokurgu": []
            "mallam fatori kessa": []
            "malam kaunari": []
            "yau": []
            "yawa kura": []
            "yituwa": []
        }
        "askira/uba": {
            "local_point": [10.6563, 13.1279]
            "askira east": []
            "chul/romirgo": []
            "dille/huyum": []
            "husara/tampul": []
            "kopa/multhafu": []
            "lassa": []
            "mussa": []
            "ngohi": []
            "ngulde": []
            "uba": []
            "uda/uvu": []
            "wamdeo/giwi": []
            "zadawa/hausari": []
        }
        "bama": {
            "local_point": [11.5218, 13.6884]
            "andara": []
            "wulba": []
            "buduwa": []
            "bula chirabe": []
            "dipchari": []
            "dar-el-jamal": []
            "kotembe": []
            "gulumba": []
            "wuro bara": []
            "kumshe": []
            "nduguno": []
            "malam": []
            "mastari": []
            "abbaram": []
            "marka": []
            "malge": []
            "amchaka": []
            "mbuliya": []
            "goniri": []
            "siraja": []
            "soye": []
            "bulongu": []
            "shehuri": []
            "wulba": []
            "ndine soho": []
            "chachile": []
            "yabiri": []
            "kura": []
            "chongolo": []
            "zangeri"
            "kash kash bulali": []
        }
        "bayo": {
            "local_point": [10.2729, 11.6613]
            "balbaya": []
            "briyel": []
            "fikayel": []
            "gamadadi": []
            "jara dali": []
            "jara gol": []
            "limanti": []
            "teli": []
            "wuyo": []
            "zara": []
        }
        "biu": {
            "local_point": [10.6117, 12.1919]
            "Buratai": []
            "Dadin Kowa": []
            "Dugja": []
            "Garubula": []
            "Gur": []
            "Kenken": []
            "Mandara Girau": []
            "Miringa": []
            "Sulumthla": []
            "Yawi": []
            "Zarawuyaku": []
        }
        "chibok": {
            "local_point": [10.8692, 12.8476]
            "garu": []
            "likama": []
            "wuntaku": []
            "gatamarwa": []
            "kautikari": []
            "korongilim": []
            "kuburmbula": []
            "mbalala": []
            "mboa kura": []
            "pemi": []
            "shikarkir": []
        }
        "damboa": {
            "local_point": [11.1561, 12.7566]
            "ajign b": []
            "ajign ii": []
            "azir multe/forfor": []
            "yerwa": []
            "ngurna/bego": []
            "gumsuri/misakurbudu": []
            "kafa": []
            "Nguda": []
            "wuyaram": []
            "wawa/korede": []
        }
        "dikwa": {
            "local_point": [12.042, 13.9173]
            "boboshe": []
            "dikwa": []
            "gajibo": []
            "magarta/sheffri": []
            "mallam maja": []
            "mudu": []
            "Kaza": []
            "muliye: []
            "jemuri": []
            "ngudoram": []
            "sogoma": []
            "afuye": []
            "Ufaye/Gujile": []
        }
        "gubio": {
            "local_point": [12.4955, 12.7796]
            "ardimini": []
            "dabira": []
            "felo": []
            "gamowo": []
            "gazabure": []
            "gubio town i": []
            "gubio town ii": []
            "kingowa": []
            "ngetra": []
            "nguru": []
            "zowo": []
        }
        "guzamala": {
            "local_point": [12.8817, 13.2202]
            "aduwa": []
            "gudumbali east": []
            "gudumbali west": []
            "guworam": []
            "guzamala east": []
            "guzamala west": []
            "kingarwa": []
            "mairari": []
            "moduri": []
            "wamiri": []
        }
        "gwoza": {
            "local_point": [12.8817, 13.2202]
            "ashigashiya": []
            "bita/izge": []
            "dure": []
            "wala/warabe": []
            "gava/agapalwa": []
            "guduf": []
            "hausari": []
            "bulabulin": []
            "New Settlement": []
            "chikide": []
            "kughum": []
            "Kirawa": []
            "Kuranabassa": []
            "ngoshe": []
            "Pulka/bokko": []
        }
        "hawul": {
            "local_point": [10.4676, 12.3464]
            "bilingwi": []
            "dzar/ vinadum/ birni/ dlandi": []
            " gwanzang pusda": []
            "hizhi": []
            "kida": []
            " kwajaffa/hang": []
            " kwaya-bur/tanga rumta": []
            " marama/kidang": []
            " pama/whitambaya": []
            " puba/vidau/lokoja": []
            " sakwa/hema": []
            "shaffa": []
        }
        "jere": {
            "local_point": [11.8948, 13.2202]
            "alau": []
            "bale galtimari": []
            "dala lawanti": []
            "dusuman": []
            "gomari": []
            "gongulong": []
            "maimusari": []
            "mairi": []
            "mashamari": []
            "ngudaa/addamari": []
            "old maiduguri": []
            "tuba": []
        }
        "kaga": {
            "local_point": [11.5246, 12.5298]
            "afa/dig/maudori": []
            "benisheikh": []
            "borgozo": []
            "dogoma / jalori": []
            "dongo": []
            "galangi": []
            "guwo": []
            "karagawaru": []
            "mainok": []
            "marguba": []
            "ngamdu": []
            "shettimari": []
            "tobolo": []
            "wajiro/burgumma": []
            "wassaram": []
            "lamboa": []
        }
        "kala/balge": {
            "local_point": [12.0825, 14.4672]
            "Jarawa/sangaya": []
            "Jilbe a": []
            " Jilbe b/koma Kaudi": []
            "Kala": []
            "Kumaga": []
            "Mada": []
            "Moholo": []
            " Rann a: []
            " Rann b/daima": []
            " Sigal/karche": []
        }
        "konduga": {
            "local_point": [11.6549, 13.4197]
            "kasugula": []
            "ajiri": []
            "auno": []
            "dalori": []
            "dawa east": []
            "malari": []
            "kawuri": []
            "ngalbiamari": []
            "mairamri": []
            "bazamri": []
            "yaleri": []
            "masba": []
            "dalwa west": []
            "yajiwa": []
            "yale/kelumiri": []
        }
        "kukawa": {
            "local_point": [12.9200, 13.5700]
            "alagarno": []
            "baga": []
            "bundur": []
            "dogoshi": []
            "doro / duguri": []
            "kauwa": []
            "kekeno": []
            "kukawa": []
            "moduari / barwari": []
            "yoyo": []
        }
        "kwaya kusar": {
            "local_point": [10.49577, 11.83711]
            "gondi": []
            "gusi / billa": []
            "guwal": []
            "kubuku": []
            "kurba": []
            "peta": []
            "wada": []
            "wawa": []
            "yimirthalang": []
        }
        "mafa": {
            "local_point": [11.924, 13.5987]
            "abbari": []
            "anadua": []
            "gawa": []
            "koshebe": []
            "laje": []
            "limanti": []
            "loskuri": []
            "ma'afa": []
            "masu": []
            "mujigine": []
            "tamsu ngamdua": []
        }
        "magumeri": {
            "local_point": [12.1151, 12.8256]
            "ardo ram": []
            "ayi / yasku": []
            "borno yesu": []
            "furram": []
            "gaji ganna i": []
            "gaji ganna ii": []
            "hoyo / chin gowa": []
            "kalizoram / banoram": []
            "kareram": []
            "kubti": []
            "ngamma": []
            "ngubala": []
        }
        "maiduguri": {
            "local_point": [11.8407, 13.1537]
            "bolori i": []
            "bolori ii": []
            "bulablin": []
            "fezzan": []
            "gamboru liberty": []
            "gwange i": []
            "gwange ii": []
            "gwange iii": []
            "hausari/zango": []
            "lamisula/jabba mari": []
            "limanti": []
            "mafoni": []
            "maisandari": []
            "shehuri north": []
            "shehuri south": []
        }
        "marte": {
            "local_point": [12.3641, 13.8277]
            "ala": []
            "alla lawanti": []
            "borsori": []
            "gumna": []
            "kabulawa": []
            "kirenowa": []
            "kulli": []
            "marte": []
            "mawulli": []
            "musune": []
            "ngeleiwa": []
            "njine": []
            "zaga": []
        }
        "mobbar": {
            "local_point": [13.133, 12.7135]
            "asaga": []
            "bogum": []
            "chamba": []
            "damasak": []
            "duji": []
            "gashagar": []
            "kareto": []
            "layi": []
            "zanna umorti": []
            "zari": []
        }
        "monguno": {
            "local_point": [12.6729, 13.616]
            "Damakuli": []
            "Kaguram": []
            "Kumalia": []
            "Mandala": []
            "Mintar": []
            "Mofio": []
            "Monguno": []
            "Ngurno": []
            "Sure": []
            "Wulo": []
            "Yele": []
            "Zulum": []
        }
        "ngala": {
            "local_point": [12.3421, 14.1858]
            "fuye": []
            "gamboru 'b'": []
            "gamboru 'c'": []
            "logumane": []
            "ndufu": []
            "ngala ward": []
            "old gamboru 'a'": []
            "sagir": []
            "tunokalia": []
            "warshele": []
            "wulgo": []
            "wurge": []
        }
        "nganzai": {
            "local_point": [12.5736, 13.0818]
            "sabsabuwa": []
            "alarge": []
            "badu": []
            "damaram": []
            "gadai": []
            "gajiram": []
            "jigalta": []
            "kuda": []
            "kurnawa": []
            "maiwa": []
            "miye": []
            "sugundure": []
        }
        "shani": {
            "local_point": [10.2227, 12.0518]
            "bargu / burashika": []
            "buma": []
            "gasi / salifawa": []
            "gora": []
            "gwalasho": []
            "gwaskara": []
            "kombo": []
            "kubo": []
            "kwaba": []
            "walama": []
        }
    }
    "cross river": {
          "abi": {
            "local_point": [5.9066, 8.038]
            "adadama": []
            "afafanyi/igonigoni": []
            "ebom": []
            "ediba": []
            "ekureku i": []
            "ekureku ii": []
            "imabana i": []
            "imabana ii": []
            "itigidi": []
            "usumutong": []
        }
        "akamkpa": {
            "local_point": [5.319, 8.3499]
            "awi": []
            "aku": []
            "iko": []
            "ikpai": []
            "mbarakom": []
            "oban": []
            "ojuk north": []
            "ojuk south": []
            "uyanga": []
        }
        "akpabuyo": {
            "local_point": [4.8808, 8.5282]
            "atimbo east": []
            "atimbo west": []
            "eneyo": []
            "idundu/anyanganse": []
            "ikang central": []
            "ikang north": []
            "ikang south": []
            "ikot edem odo": []
            "ikot eyo": []
            "ikot nakanda": []
        }
        "bakassi": {
            "local_point": [4.81714, 8.60212]
            "abana": []
            "akpankanya": []
            "akwa": []
            "ambai ekpa": []
            "amoto": []
            "archibong": []
            "atai ema": []
            "efut inwang": []
            "ekpot abia": []
            "odiong": []
        }
        "bekwarra": {
            "local_point": [6.69, 8.9025]
            "abuochiche": []
            "afrike ochagbe": []
            "afrike okpeche": []
            "beten": []
            "gakem": []
            "ibiaragidi": []
            "nyanya": []
            "otukpuru": []
            "ugboro": []
            "ukpah": []
        }
        "biase": {
            "local_point": [5.5483, 8.0902]
            "abayong": []
            "adim": []
            "agwagune/okurike": []
            "akpet/abini": []
            "biakpan": []
            "ehom": []
            "erei north": []
            "erei south": []
            "ikun/etono": []
            "umon north": []
            "umon south": []
        }
        "boki": {
            "local_point": [6.2467, 8.9245]
            "abo": []
            "alankwe": []
            "beebo/bumaji": []
            "boje": []
            "buda": []
            "buentsebe": []
            "bunyia/okubuchi": []
            "ekpashi": []
            "kakwagom/bawop": []
            "ogep/osokom": []
            "oku/borum/njua": []
        }
        "calabar municipal": {
            "local_point": [5.0166, 8.3636]
        }
        "calabar south": {
            "local_point": [4.8627, 8.3307]
        }
        "etung": {
            "local_point": [5.8717, 8.7922]
            "abia": []
            "abijang": []
            "agbokim": []
            "ajassor": []
            "bendeghe ekiem": []
            "effraya": []
            "etomi": []
            "itaka": []
            "mkpot/ayuk aba": []
            "nsofang": []
        }
        "ikom": {
            "local_point": [5.9617, 8.7206]
            "abanyum": []
            "akparabong": []
            "nde": []
            "nnam": []
            "nta/nselle": []
            "ofutop i": []
            "ofutop ii": []
            "olulumo": []
            "yala/nkum": []
        }
        "obanliku": {
            "local_point": [6.5344, 9.3229]
            "basang": []
            "bebi": []
            "becheve": []
            "bendi i": []
            "bendi ii": []
            "bishiri north": []
            "bishiri south": []
            "bisu": []
            "busi": []
        }
        "obubra": {
            "local_point": [6.082, 8.3278]
            "ababene": []
            "apiapum": []
            "iyamoyong": []
            "ochon": []
            "ofat": []
            "ofodua": []
            "ofumbongha/yala": []
            "osopong i": []
            "osopong ii": []
            "ovonum": []
        }
        "obudu": {
            "local_point": [6.6694, 9.1622]
            "alege/ubang": []
            "angiaba / begiaka": []
            "begiading": []
            "ipong": []
            "ukpe": []
            "utugwang central": []
            "utugwang north": []
            "utugwang south": []
        }
        "odukpani": {
            "local_point": [5.0812, 8.3499]
            "adiabo/efut": []
            "akamkpa": []
            "creek town i": []
            "creek town ii": []
            "eki": []
            "ekori/anaku": []
            "eniong": []
            "ikoneto": []
            "ito/idere/ukwa": []
            "obomitiat/mbiabo/ediong": []
            "odot": []
            "oniman-kiong": []
        }
        "ogoja": {
            "local_point": [6.6548, 8.7977]
            "ekajuk i": []
            "ekajuk ii": []
            "mbube east i": []
            "mbube east ii": []
            "mbube west i": []
            "mbube west ii": []
            "nkum iborr": []
            "nkum irede": []
        }
        "yakurr": {
            "local_point": [5.7973, 8.1776]
            "abanakpai": []
            "afrekpe/ekpenti": []
            "ajere": []
            "assiga": []
            "biko biko": []
            "idomi": []
            "ijiman": []
            "ijom": []
            "ikpakapit": []
            "inyima": []
            "mkpani/agoi": []
            "nkpolo/ukpawen": []
            "ntan": []
        }
        "yala": {
            "local_point": [6.6316, 8.6161]
            "echumofana": []
            "gabu": []
            "ijiraga": []
            "njrigom/mfuma": []
            "okpoma": []
            "okuku": []
            "wanakom": []
            "wanihem": []
            "wanikade": []
            "yache": []
            "yahe": []
        }
    }
    "delta": {
        "aniocha north": {
            "local_point": []
            "ezi": []
            "idumuje - unor": []
            "issele - azagba": []
            "issele uku i": []
            "issele uku ii": []
            "obior": []
            "obomkpa": []
            "onicha - olona": []
            "onicha ugbo": []
            "ukwu - nzu": []
        }
        "aniocha south": {
            "local_point": []
            "aba - unor": []
            "ejeme": []
            "isheagu-ewulu": []
            "nsukwa": []
            "ogwashi - uku i": []
            "ogwashi - uku ii": []
            "ogwashi - uku village": []
            "ubulu - uku i": []
            "ubulu - uku ii": []
            "ubulu - unor": []
            "ubulu okiti": []
        }
        "bomadi": {
            "local_point": []
            "akugbene i": []
            "akugbene ii": []
            "akugbene iii": []
            "kolafiogbene/ekametagbene": []
            "kpakiama": []
            "ogbeinama/okoloba": []
            "ogo - eze": []
            "ogriagbene": []
            "syama": []
        }
        "burutu": {
            "local_point": []
            "bulou - ndoro": []
            "ngbilebiri i": []
            "ngbilebiri ii": []
            "obotebe": []
            "ogbolubiri": []
            "ogulagha": []
            "ojobo": []
            "seimbiri": []
            "tamigbe": []
            "torugbene": []
            "tuomo": []
        }
        "ethiope east": {
            "local_point": []
            "abraka": []
            "agbon": []
        }
        "ethiope west": {
            "local_point": []
            "jesse": []
            "mosogar": []
            "oghara": []
        }
        "ika north east": {
            "local_point": []
            "akumazi": []
            "idumuesah": []
            "igbodo": []
            "mbiri": []
            "otolokpo": []
            "owa": []
            "umunede": []
            "ute - ogbeje": []
            "ute - okpu": []
        }
        "ika south": {
            "local_point": []
            "abavo": []
            "agbor": []
            "boji - boji": []
            "ekuku - agbor": []
            "ihiuiyase": []
            "ihuozomor (ozanogogo alisimie)": []
        }
        "isoko north": {
            "local_point": []
            "ellu": []
            "emevor": []
            "iluelogbo": []
            "iyede": []
            "okpe - isoko": []
            "otibio": []
            "ovrode": []
            "owhe/akiehwe": []
            "oyede": []
            "ozoro": []
        }
        "isoko south": {
            "local_point": []
            "aviara": []
            "emede": []
            "enhwe/okpolo": []
            "erowa/umeh": []
            "igbide": []
            "igbide": []
            "oleh": []
            "olomoro": []
            "uzere": []
        }
        "ndokwa east": {
            "local_point": []
            "abarra/inyi/onuaboh": []
            "aboh/akarrai": []
            "afor/obikwele": []
            "ase": []
            "ashaka": []
            "ibedeni": []
            "ibrede/igbuku / onogbokor": []
            "okpai/utchi/beneku": []
            "onyia/adiai/otuoku/umuolu": []
            "ossissa": []
        }
        "ndokwa west": {
            "local_point": []
            "abbi": []
            "emu": []
            "ogume": []
            "onicha - ukwani": []
            "utagba ogbe": []
            "utagba uno": []
        }
        "okpe": {
            "local_point": []
            "aghalokpe": []
            "aragba town": []
            "mereje": []
            "oha": []
            "orerokpe": []
            "oviri - okpe": []
            "ughoton": []
        }
        "oshimili north": {
            "local_point": []
            "akwukwu": []
            "ebu": []
            "ibusa": []
            "illah": []
            "okpanam": []
            "ukala": []
        }
        "oshimili south": {
            "local_point": []
            "agu": []
            "anala-amakom": []
            "cable point": []
            "ogbele/akpako": []
            "okwe": []
            "ugbomanta quarters": []
            "umuaji": []
            "umuezei": []
            "umuonaje": []
            "west end": []
        }
        "patani": {
            "local_point": []
            "abari": []
            "ogoloma": []
            "bolou - angiama": []
            "odorubu/adobu/bolou apelebri": []
            "taware/kolowara aven": []
            "toru-angiama": []
            "uduophori": []
        }
        "sapele": {
            "local_point": []
            "amuokpe": []
            "elume": []
            "okokporo/ugborhen": []
        }
        "udu": {
            "local_point": []
            "aladja": []
            "ekete": []
            "opete/assagba/edjophe": []
            "orhuwerun": []
            "ovwian": []
        }
        "ughelli north": {
            "local_point": []
            "agbarha": []
            "agbarho": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "ughelli south": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "ukwuani": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "uvwie": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "warri north": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "warri south": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
        "warri south west": {
            "local_point": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
            "area_1": []
        }
    }
}